apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
  clusterIP: None      
---
# statefulset
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  serviceName: mysql
  replicas: 1
  selector:
    matchLabels:
      app: mysql # has to match .spec.template.metadata.labels
  template:
    metadata:
      labels:
        app: mysql
    spec:
      restartPolicy: Always
      containers:
      - image: mysql:8.0.32
        name: mysql
        # livenessProbe:
        #   exec:
        #     command:
        #       - ls
        #       - /var/lib/mysql/lost+found
        #   initialDelaySeconds: 5
        #   periodSeconds: 5
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: tcomp#mysql
        - name: MYSQL_DATABASE
          value: "school"          
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-pvc
          mountPath: /var/lib/mysql
        - name: mysql-initdb
          mountPath: /docker-entrypoint-initdb.d          
        resources: {}
      volumes:
      - name: mysql-pvc
        persistentVolumeClaim:
          claimName: mysql-pvc
      - name: mysql-initdb
        configMap:
          name: mysql-initdb-config          