apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd-main
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc   
  syncPolicy:
    automated: {}